[tool.usort]

categories = [
    "future",
    "standard_library",
    "third_party",
    # PyTorch core needs to imported before any other PyTorch derivative, because it does some magic in the background.
    "pytorch_core",
    "first_party",
    # This category are contains local utility modules from our references/ and test/ folder. usort mistakes them for
    # third party packages if we don't specify them manually.
    "local_utils",
]

[tool.usort.known]

pytorch_core = ["torch"]

local__utils = [
    "_utils_internal",
    "coco_utils",
    "common_utils",
    "datasets_utils",
    "engine",
    "group_by_aspect_ratio",
    "loss",
    "model",
    "presets",
    "sampler",
    "scheduler",
    "utils",
]

[tool.black]

line-length = 120
target-version = ["py36"]

[tool.ufmt]

excludes = [
    "gallery",
]
