[tool.usort]

categories = [
    "future",
    "standard_library",
    "third_party",
    "pytorch",
    "first_party",
    "local_test_utils",
]

[tool.usort.known]

pytorch = ["torch"]
first_party = ["torchvision"]
# These are local utilities in our test/ folder. Since that folder is not a Python package, i.e. test/__init__.py is
# missing, usort mistakes these modules as third party packages.
local_test_utils = [
    "_utils_internal",
    "common_utils",
    "dataset_utils",
]

[tool.black]

line-length = 120
target-version = ["py36"]

[tool.ufmt]

excludes = [
    "gallery",
]
