[tool.usort]

categories = [
    "future",
    "standard_library",
    "third_party",
    "pytorch",
    "first_party",
    "local_utils",
]

[tool.usort.known]

pytorch = ["torch"]
first_party = ["torchvision"]
local_utils = [
    "_utils_internal",
    "common_utils",
    "dataset_utils",
]

[tool.black]

line-length = 120
target-version = ["py36"]

[tool.ufmt]

excludes = [
    "gallery",
]
