[tool.usort]

categories = [
    "future",
    "standard_library",
    "third_party",
    "pytorch",
    "pytorch_derivatives",
    "first_party",
]

# This flag is needed to group torchvision into 'pytorch_derivatives' rather than 'first_party'
first_party_detection = false

[tool.usort.known]

pytorch = ["torch"]
pytorch_derivatives = ["torchvision"]
# These are local utilities in our test/ folder. Since that folder is not a Python package, i.e. test/__init__.py is
# missing, usort mistakes these modules as third party packages.
first_party = [
    "_utils_internal",
    "common_utils",
    "dataset_utils",
]

[tool.black]

line-length = 120
target-version = ["py36"]

[tool.ufmt]

excludes = [
    "gallery",
]
