channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - pytest
  - pytest-cov
  - pytest-mock
  - pip
  - libpng
  - libjpeg-turbo
  - ca-certificates
  - h5py
  - pip:
    - future
    - scipy
    - av
