channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - pytest
  - pytest-cov
  - pytest-mock
  - pip
  - libpng
  - jpeg-turbo
  - ca-certificates
  - h5py
  - pip:
    - future
    - pillow >=5.3.0, !=8.3.*
    - scipy
    - av
