channels:
  - pytorch
  - defaults
  - malfet
dependencies:
  - pytest
  - pytest-cov
  - pytest-mock
  - pip
  - libpng
  - jpeg
  - ca-certificates
  - h5py
  - pip:
    - future
    - scipy
    - av < 10
