channels:
  - pytorch
  - defaults
dependencies:
  - numpy
  - pytest
  - pytest-cov
  - codecov
  - pip
  - libpng
  - jpeg
  - ffmpeg
  - ca-certificates
  - pip:
    - future
    - pillow>=4.1.1
    - scipy
    - av