channels:
  - defaults
dependencies:
  - numpy
  - pytest
  - pytest-cov
  - codecov
  - pip
<<<<<<< HEAD
  # Required by the image extension
  - libpng
=======
>>>>>>> upstream/master
  - ca-certificates
  - pip:
    - future
    - pillow>=4.1.1
    - scipy
    - av