# checkpoint dir
checkpoint_dir: "/fsx/users/teodorponcu/checkpoints/crestereo"

# from where to resume the training
resume: null

# train dataset parameters
dataset_root: "/fsx/users/teodorponcu/datasets"
train_dataset: ["crestereo"]
dataset_steps: [300_000]
transforms: "cre-high-scale"

# dataloader parameters
workers: 16
threads: 16

# shuffle samples inside a dataset
dataset_shuffle: True
# shuffles samples schedule datasets, implies that schedule
# will not be respected any longer
schedule_shuffle: False

# batch size
batch_size: 2

# validation datasets
valid_dataset: ["middlebury2014-train"]
valid_freq: 10_000
save_freq: 10_000

# optimizer
lr: 4.0e-4
min_lr: 4.0e-6
lr_warmup_decay: 1.0e-2
lr_decay_gamma: 0.88

wd: 0.0
clip_grad_norm: 0.0

# learning rate scheduler
warmup_steps: 6_000
flat_lr_steps: 120_000
period_lr_steps: 30_000
period_lr_mult: 1

lr_warmup_method: linear
lr_decay_method: cosine-restart

# model
model: "crestereo_base"

# architecture speciffic parameters
recurrent_updates: 5
freeze_batch_norm: True

# loss speciffic parameters
gamma: 0.995
consistency_alpha: 0.0

# mixed precision parameters
mixed_precison: True

# objective modelling speciffic
should_learn_y_flow: True

# distributed parameters
dist_url: "env://"
world_size: 8
device: "cuda"

mixed_precision: False

# deterministic behaviour
seed: 42
use_deterministic_algorithms: False


# weights API
weights: null

tensorboard_summaries: True
write_summary_freq: 100