channels:
  - pytorch
  - defaults
  # use conda-forge for python v3.9+
  - conda-forge
dependencies:
  - pytest
  - pytest-cov
  - codecov
  - pip
  - libpng
  # NOTE: Pinned to fix issues with size_t on Windows
  - jpeg <=9b
  - ca-certificates
  - pip:
    - future
    - pillow>=4.1.1
    - scipy
    - av
    - dataclasses
