name: Build android

on:
  pull_request:
  push:
    branches:
      - nightly
      - main
      - release/*
  workflow_dispatch:

jobs:
  build:
    uses: pytorch/test-infra/.github/workflows/linux_job.yml@main
    with:
      repository: pytorch/vision
      upload-artifact: android
      script: |
        set -euo pipefail
        
        ANDROID_VERSION=28
        ANDROID_NDK_VERSION=21.1.6352462
        GRADLE_VERSION=6.8.3
        
        echo '::group::Setup Java'
        yum install -y java-11-openjdk-devel
        echo '::endgroup::'
        
        echo '::group::Setup Android SDK'
        wget --no-verbose https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
        mkdir -p android-sdk/cmdline-tools
        unzip cmdline-tools.zip -d android-sdk/cmdline-tools
        mv android-sdk/cmdline-tools/cmdline-tools android-sdk/cmdline-tools/latest
        SDKMANAGER="./android-sdk/cmdline-tools/latest/bin/sdkmanager"
        yes | "${SDKMANAGER}" --licenses || true
        "${SDKMANAGER}" --install "platforms;android-${ANDROID_VERSION}" "ndk;${ANDROID_NDK_VERSION}"
        echo '::endgroup::'

        echo '::group::Setup gradle'
        wget --no-verbose "https://downloads.gradle-dn.com/distributions/gradle-${GRADLE_VERSION}-bin.zip" -O gradle.zip
        unzip gradle.zip
        export ANDROID_SDK_ROOT=android-sdk
        export ANDROID_NDK_ROOT=android-sdk/ndk
        GRADLE="./gradle-${GRADLE_VERSION}/bin/gradle"
        echo '::endgroup::'
        
        echo '::group::Build'
        ${GRADLE} --no-daemon -p android assemble
        find android -type f -name "*aar" | xargs tar -cfv "${RUNNER_ARTIFACT_DIR}/aars.tar"
        find android -type f -name "*apk" | xargs tar -cfv "${RUNNER_ARTIFACT_DIR}/apks.tar"
        echo '::endgroup::'
