on:
  pull_request:

jobs:
  debug:

    runs-on: macos-12

    defaults:
      run:
        shell: bash -el {0}

    steps:
      - name: Set up miniconda
        uses: conda-incubator/setup-miniconda@v2

      - name: Uninstall system libs
        run: |
          JPEG_LIBS=$(brew list | grep jpeg)
          echo $JPEG_LIBS
          for lib in $JPEG_LIBS; do
            brew uninstall --ignore-dependencies --force $lib || true
          done

      - name: Create build environment
        run: |
          conda install --quiet python=3.10 pip libpng jpeg ffmpeg=4.2 ninja
          pip install --progress-bar=off --upgrade setuptools light-the-torch
          ltt install --progress-bar=off --pytorch-channel=nightly torch
          python -m torch.utils.collect_env

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: build torchvision
        run: |
          python setup.py develop
          python setup.py bdist_wheel

      - name: delocate
        run: |
          pip install --progress-bar=off delocate
          export DYLD_FALLBACK_LIBRARY_PATH="${CONDA_PREFIX}/lib"
          delocate-path --ignore-missing-dependencies torchvision
          delocate-wheel -v --ignore-missing-dependencies dist/*.whl

      - name: Test
        run: |
          pip install --progress-bar=off pytest pytest-mock
          pytest -v test/test_image.py -k jpeg

      - name: Setup tmate session
        if: always()
        uses: mxschmitt/action-tmate@v3
