on:
  pull_request:

jobs:
  debug:

    runs-on: macos-12

    defaults:
      run:
        shell: bash -el {0}

    steps:
      - name: Set up miniconda
        uses: conda-incubator/setup-miniconda@v2

      - name: Create build environment
        run: |
          conda install --quiet python=3.10 pip libpng jpeg ffmpeg=4.2 ninja
          pip install --progress-bar=off --upgrade setuptools light-the-torch
          ltt install --progress-bar=off --pytorch-channel=nightly torch
          python -m torch.utils.collect_env

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: build torchvision
        run: python setup.py develop

      - name: Test
        run: |
          pip install --progress-bar=off pytest pytest-mock
          pytest -v test/test_image.py -k jpeg

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
