name: tests

on:
  pull_request:

jobs:
  prototype:
    strategy:
      matrix:
        os:
          - ubuntu-latest
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      - name: Set up python
        uses: actions/setup-python@v3
        with:
          python-version: 3.7

      - name: Upgrade system packages
        run: python -m pip install --upgrade pip setuptools wheel

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install PyTorch nightly builds
        run: pip install --progress-bar=off --pre torch torchdata --extra-index-url https://download.pytorch.org/whl/nightly/cpu/

      - name: Install torchvision
        run: pip install --progress-bar=off --no-build-isolation --editable .

      - name: Install other prototype dependencies
        run: pip install --progress-bar=off scipy pycocotools h5py iopath

      - name: Install test requirements
        run: pip install --progress-bar=off pytest pytest-mock pytest-cov

      - name: Mark setup as complete
        id: setup
        run: exit 0

      - name: Test non-determinism
        run: |
          pip install tqdm
          python test_gaussian_blur_non_determinism.py

      - name: Run prototype transforms tests
        if: success() || ( failure() && steps.setup.conclusion == 'success' )
        shell: bash
        run: pytest -rP test/test_prototype_transforms_functional.py::TestKernels::test_scripted_vs_eager -k gauss

      - name: Upload test inputs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-inputs
          path: test/artifacts
