name: tests

on:
  pull_request:

jobs:
  prototype:
    permissions: write-all

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Set up python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8

      - name: Upgrade system packages
        run: python -m pip install --upgrade pip setuptools wheel

      - name: Checkout repository
        uses: actions/checkout@v3

#      - name: Install PyTorch nightly builds
#        run: pip install --progress-bar=off --pre torch torchdata --extra-index-url https://download.pytorch.org/whl/nightly/cpu/
#
#      - name: Install torchvision
#        run: pip install --progress-bar=off --no-build-isolation --editable .
#
#      - name: Install other prototype dependencies
#        run: pip install --progress-bar=off scipy pycocotools h5py iopath

      - name: Install test requirements
        run: pip install --progress-bar=off pytest pytest-mock

#      - name: Run prototype tests
#        shell: bash
#        run: pytest --junitxml=test-results/junit.xml --durations 20 test/test_prototype_*.py

      - name: Run prototype tests
        shell: bash
        run: pytest --junitxml=test-results/junit.xml --durations 20 test_foo.py

      - name: Debug
        if: always()
        shell: bash
        run: cat ./test-results/junit.xml

      - name: Report test results
        uses: dorny/test-reporter@v1.5.0
        if: always()
        with:
          name: prototype tests
          path: ./test-results/junit.xml
          reporter: java-junit
          fail-on-error: false
