name: tests

on:
  pull_request:

jobs:
  prototype:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      - name: Set up python
        uses: actions/setup-python@v3
        with:
          python-version: 3.7

      - name: Generate cache params
        id: cache-params
        shell: bash
        env:
          # TODO: explain
          HOUR: 10
        run: |
          CACHE_PATH=`python -c 'import sys; print("\n".join(path for path in sys.path if path))'`
          echo $CACHE_PATH
          echo "::set-output name=path::$CACHE_PATH"
          
          if (( `date -u '+%-H'` > $HOUR )); then DATE='today'; else DATE='yesterday'; fi
          echo $DATE
          CACHE_DATE=`date -u --date=$DATE '+%Y%m%d'`
          echo $CACHE_DATE
          echo "::set-output name=date::$CACHE_DATE"

#      - name: Get pip cache path
#        id: get-cache-path
#        shell: bash
#        run: |
#          pip install appdirs
#          CACHE_PATH=`python -c "import appdirs; print(appdirs.user_cache_dir('pip', appauthor=False))"`
#          echo "pip cache stored in ${CACHE_PATH}"
#          echo "::set-output name=path::$CACHE_PATH"

      - name: Restore pip cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.cache-params.outputs.path }}
          key: ${{ runner.os }}-${{ steps.cache-params.outputs.date }}
#
#      - name: Checkout repository
#        uses: actions/checkout@v3
#
#      - name: Install PyTorch nightly builds
#        run: pip install --progress-bar=off --pre torch torchdata --extra-index-url https://download.pytorch.org/whl/nightly/cpu/
#
#      - name: Install torchvision
#        run: pip install --progress-bar=off --no-build-isolation --editable .
#
#      - name: Install other prototype dependencies
#        run: pip install --progress-bar=off scipy pycocotools h5py iopath
#
#      - name: Install test requirements
#        run: pip install --progress-bar=off pytest pytest-mock
#
#      - name: Run prototype tests
#        shell: bash
#        run: pytest --durations=20 test/test_prototype_*.py
