name: tests

on:
  pull_request:

jobs:
  prototype:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        python-version:
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
        flag:
          - "--pre"
          - ""
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      - name: Set up python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade system packages
        run: python -m pip install --upgrade pip setuptools wheel

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install PyTorch nightly builds
        run: pip install --progress-bar=off --pre torchdata torch --extra-index-url https://download.pytorch.org/whl/nightly/cpu/

      - name: Upgrade numpy
        run: pip install --upgrade ${{ matrix.flag }} numpy

      - name: Install torchvision
        run: pip install --progress-bar=off --no-build-isolation --editable .

      - name: Install other prototype dependencies
        run: pip install --progress-bar=off scipy pycocotools h5py

      - name: Install test requirements
        run: pip install --progress-bar=off pytest pytest-mock pytest-cov

      - name: Mark setup as complete
        id: setup
        run: exit 0

      - name: Run prototype datasets tests
        shell: bash
        run: |
          pytest \
            --durations=20 \
            --cov=torchvision/prototype/datapoints \
            --cov-report=term-missing \
            test/test_prototype_datasets*.py
