name: Tests on macOS

on:
  pull_request:
  push:
    branches:
      - nightly
      - main
      - release/*
  workflow_dispatch:

jobs:
  unittests:
    strategy:
      matrix:
        include:
          # Test against the most popular version of Python (at the time of commit 40% of torch downloads use 3.8)
          - python-version: "3.8"
            runner: "macos-12"
          # Minimum version available for Apple Silicon is 3.9, so just use that
          - python-version: "3.9"
            runner: "macos-m1-12"
      fail-fast: false
    uses: pytorch/test-infra/.github/workflows/macos_job.yml@main
    with:
      repository: pytorch/vision
      # We need an increased timeout here, since the macos-12 runner is the free one from GH
      # and needs roughly 2 hours to just run the test suite
      timeout: 240
      runner: ${{ matrix.runner }}
      script: |
        set -euo pipefail

        export PYTHON_VERSION=${{ matrix.python-version }}
        export GPU_ARCH_TYPE=cpu
        export GPU_ARCH_VERSION=''

        ./.github/scripts/unittest.sh
