name: Tests on Windows

on:
  pull_request:
  push:
    branches:
      - nightly
      - main
      - release/*
  workflow_dispatch:

jobs:
  unittests:
    strategy:
      matrix:
        python-version:
          - "3.8"
        runner: ["windows.4xlarge"]
        gpu-arch-type: ["cpu"]
      fail-fast: false
    uses: pytorch/test-infra/.github/workflows/windows_job.yml@win-conda
    with:
      repository: pytorch/vision
      runner: ${{ matrix.runner }}
      timeout: 120
      script: |
        set -euo pipefail
        
        sleep 3600

        export PYTHON_VERSION=${{ matrix.python-version }}
        export GPU_ARCH_TYPE=${{ matrix.gpu-arch-type }}
        export GPU_ARCH_VERSION=${{ matrix.gpu-arch-version }}

        which conda
