name: Unit-tests on M1
on:
  pull_request:
    paths:
      - .github/workflows/test-m1.yml
  push:
    branches:
      - nightly
      - main
  workflow_dispatch:
jobs:
  tests:
    name: "Build TorchVision M1 wheels"
    runs-on: macos-m1
    strategy:
      matrix:
        py_vers: [ "3.8"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install TorchVision
        shell: arch -arch arm64 bash {0}
        env:
          ENV_NAME: conda-env-${{ github.run_id }}
          PY_VERS: ${{ matrix.py_vers }}
        run: |
          . ~/miniconda3/etc/profile.d/conda.sh
          set -ex
          conda create -yp ${ENV_NAME} python=${PY_VERS} numpy libpng openjpeg wheel pkg-config
          conda run -p ${ENV_NAME} python3 -mpip install torch --extra-index-url=https://download.pytorch.org/whl/nightly
          conda run -p ${ENV_NAME} python3 setup.py develop
          conda run -p ${ENV_NAME} python3 -mpip install pytest pytest-mock
      - name: Run tests
        shell: arch -arch arm64 bash {0}
        env:
          ENV_NAME: conda-env-${{ github.run_id }}
          PY_VERS: ${{ matrix.py_vers }}
        run: |
          . ~/miniconda3/etc/profile.d/conda.sh
          set -ex
          conda run -p ${ENV_NAME} --no-capture-output python3 -u -mpytest -v --durations 20
          conda env remove -p ${ENV_NAME}
