name: Unit-tests on M1
on:
  pull_request:

jobs:
  tests:
    name: "Build TorchVision M1 wheels"
    runs-on: macos-m1
    strategy:
      matrix:
        py_vers: [ "3.8"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run tests
        shell: arch -arch arm64 bash {0}
        env:
          ENV_NAME: conda-env-${{ github.run_id }}
          PY_VERS: ${{ matrix.py_vers }}
        run: |
          . ~/miniconda3/etc/profile.d/conda.sh
          set -ex
          export BUILD_VERSION=0.14.0.dev$(date "+%Y%m%d")
          conda create -yp ${ENV_NAME} python=${PY_VERS} numpy libpng openjpeg wheel pkg-config
          conda run -p ${ENV_NAME} python3 -mpip install torch --extra-index-url=https://download.pytorch.org/whl/nightly
          conda run -p ${ENV_NAME} python3 setup.py develop
          pytest -v --durations 20
          conda env remove -p ${ENV_NAME}
