name: Unit-tests on Linux CPU
on:
  pull_request:
  push:
    branches:
      - nightly
      - main
      - release/*
  workflow_dispatch:
env:
  CHANNEL: "nightly"
jobs:
  tests:
    name: "Unit-tests on Linux CPU"
    runs-on: [self-hosted, linux.12xlarge]
    container:
      image: pytorch/manylinux-builder:cpu
    strategy:
      matrix:
        py_vers: ["3.8"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set Release CHANNEL (for release)
        if: ${{ (github.event_name == 'pull_request' && startsWith(github.base_ref, 'release')) || startsWith(github.ref, 'refs/heads/release') }}
        run: |
          echo "CHANNEL=test" >> "$GITHUB_ENV"
      - name: Setup miniconda
        uses: pytorch/test-infra/.github/actions/setup-miniconda@main
        env:
          PY_VERS: ${{ matrix.py_vers }}
        with:
          python_version: ${PY_VERS}
      - name: Install TorchVision
        shell: bash -l {0}
        env:
          ENV_NAME: conda-env-${{ github.run_id }}
          PY_VERS: ${{ matrix.py_vers }}
          VERSION: cpu
          CUDATOOLKIT: cpuonly
        run: |
          # . ~/miniconda3/etc/profile.d/conda.sh
          # Needed for JPEG library detection as setup.py detects conda presence by running `shutil.which('conda')`
          export PATH=~/miniconda3/bin:$PATH
          set -ex
          # conda create -yp ${ENV_NAME} python=${PY_VERS} numpy libpng jpeg scipy
          # conda run -p ${ENV_NAME} conda install -y -c "pytorch-${CHANNEL}" -c nvidia "pytorch-${CHANNEL}"::pytorch[build="*${VERSION}*"] "${CUDATOOLKIT}"
          # conda run -p ${ENV_NAME} python3 setup.py develop
          # conda run -p ${ENV_NAME} python3 -mpip install pytest pytest-mock av
          ${CONDA_RUN} conda install -y -c "pytorch-${CHANNEL}" -c nvidia "pytorch-${CHANNEL}"::pytorch[build="*${VERSION}*"] "${CUDATOOLKIT}"
          ${CONDA_RUN} python3 setup.py develop
          ${CONDA_RUN} python3 -mpip install pytest pytest-mock av
      - name: Run tests
        shell: bash -l {0}
        env:
          ENV_NAME: conda-env-${{ github.run_id }}
          PY_VERS: ${{ matrix.py_vers }}
        run: |
          . ~/miniconda3/etc/profile.d/conda.sh
          set -ex
          ${CONDA_RUN} python3 -m torch.utils.collect_env
          ${CONDA_RUN} python3 -m pytest --junitxml=test-results/junit.xml -v --durations 20
