name: Tests

on:
  pull_request:

jobs:
  compile:
    strategy:
      matrix:
        dynamic:
          - true
          - false
        backend:
          - eager
          - inductor
        fullgraph:
          - true
          - false
      fail-fast: false

    uses: pytorch/test-infra/.github/workflows/linux_job.yml@main
    with:
      job-name: ${{ format('dynamic={0},backend={1},fullgraph={2}', matrix.dynamic, matrix.backend, matrix.fullgraph) }}
      repository: pytorch/vision
      runner: "linux.12xlarge"
      gpu-arch-type: "cpu"
      gpu-arch-version: ""
      timeout: 120
      test-infra-ref: main
      script: |
        set -euo pipefail

        export PYTHON_VERSION='3.8'
        export GPU_ARCH_TYPE='cpu'
        export GPU_ARCH_VERSION=''

        export COMPILE_DYNAMIC='${{ matrix.dynamic }}'
        export COMPILE_BACKEND='${{ matrix.backend }}'
        export COMPILE_FULLGRAPH='${{ matrix.fullgraph }}'

        ./.github/scripts/unittest.sh
