name: Unit-tests on Linux CPU

on:
  pull_request:
  push:
    branches:
      - nightly
      - main
      - release/*
  workflow_dispatch:

env:
  CHANNEL: "nightly"

jobs:
  tests:
    strategy:
      matrix:
        python_version: ["3.8", "3.9", "3.10", "3.11"]
      fail-fast: false
    uses: pytorch/test-infra/.github/workflows/linux_job.yml@main
    with:
      runner: linux.12xlarge
      repository: pytorch/vision
      script: |
        # Mark Build Directory Safe
        set -euxo pipefail
        git config --global --add safe.directory /__w/vision/vision

        # Set up Environment Variables
        export PYTHON_VERSION="${{ matrix.python_version }}"
        export VERSION="cpu"
        export CUDATOOLKIT="cpuonly"

        # Set CHANNEL
        if [[ (${GITHUB_EVENT_NAME} = 'pull_request' && (${GITHUB_BASE_REF} = 'release'*)) || (${GITHUB_REF} = 'refs/heads/release'*) ]]; then
          export CHANNEL=test
        else
          export CHANNEL=nightly
        fi

        # Create Conda Env
        if [[ "${PYTHON_VERSION}" = "3.11" ]]; then
          conda create -yp ci_env -c conda-forge python="${PYTHON_VERSION}" libpng jpeg
          # conda install -c pytorch-nightly numpy
          python3 -m pip install numpy
        else
          conda create -yp ci_env python="${PYTHON_VERSION}" numpy libpng jpeg
        fi
        
        conda activate /work/ci_env
        
        # Install PyTorch, Torchvision, and testing libraries
        if [[ "${PYTHON_VERSION}" = "3.11" ]]; then
          conda install \
            --yes \
            -c "pytorch-${CHANNEL}" \
            -c nvidia "pytorch-${CHANNEL}"::pytorch[build="*${VERSION}*"] \
            "${CUDATOOLKIT}"
        else
          python -m pip install --pre torch --index-url https://download.pytorch.org/whl/nightly/cpu
        fi

        python3 setup.py develop
        if [[ "${PYTHON_VERSION}" = "3.11" ]]; then
          # Looks like the av libraries are not available for 3.11
          python3 -m pip install pytest pytest-mock
          python3 -m pip install av
        else
          python3 -m pip install pytest pytest-mock 'av<10'
        fi

        # Run Tests
        python3 -m torch.utils.collect_env
        python3 -m pytest --junitxml=test-results/junit.xml -v --durations 20
