name: Unit-tests on Windows

on:
  pull_request:
  push:
    branches:
      - nightly
      - main
      - release/*
  workflow_dispatch:

jobs:
  tests:
    strategy:
      matrix:
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
        runner: [ "windows.4xlarge" ]
        include:
          - python-version: 3.8
            runner: windows.8xlarge.nvidia.gpu
      fail-fast: false
    uses: pytorch/test-infra/.github/workflows/windows_job.yml@main
    with:
      repository: pytorch/vision
      runner: ${{ matrix.runner }}
      timeout: 120
      script: |
        export PYTHON_VERSION=${{ matrix.python-version }}
        
        sleep 3600

        ./.github/unittest.sh
