name: Unit-tests on Windows

on:
  pull_request:
  push:
    branches:
      - nightly
      - main
      - release/*
  workflow_dispatch:

jobs:
  tests:
    strategy:
      matrix:
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
        runner: ["windows.4xlarge"]
        gpu-arch-type: ["cpu"]
        include:
          - python-version: 3.8
            runner: windows.8xlarge.nvidia.gpu
            gpu-arch-type: "cuda"
            gpu-arch-version: "11.7"
      fail-fast: false
    uses: pytorch/test-infra/.github/workflows/windows_job.yml@windows-generic-conda
    with:
      repository: pytorch/vision
      test-infra-ref: windows-generic-conda
      runner: ${{ matrix.runner }}
      timeout: 120
      script: |
        export PYTHON_VERSION=${{ matrix.python-version }}
        export GPU_ARCH_TYPE=${{ matrix.gpu-arch-type }}
        export GPU_ARCH_VERSION=${{ matrix.gpu-arch-version }}
        
        ./.github/unittest.sh
