name: Tests on Windows

on:
  pull_request:
  push:
    branches:
      - nightly
      - main
      - release/*
  workflow_dispatch:

jobs:
  unittests:
    strategy:
      matrix:
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
        runner: ["windows.4xlarge"]
        gpu-arch-type: ["cpu"]
        include:
          - python-version: "3.8"
            runner: windows.8xlarge.nvidia.gpu
            gpu-arch-type: cuda
            # For now the Windows job only supports CUDA 11.8. We want to test the "stable" CUDA here,
            # i.e. CUDA 11.7, as we do for Linux, but testing any CUDA is better than none.
            # FIXME: Switch this to "11.7" as soon the the Windows job supports selecting a CUDA version
            gpu-arch-version: "11.8"
      fail-fast: false
    uses: pytorch/test-infra/.github/workflows/windows_job.yml@main
    with:
      repository: pytorch/vision
      runner: ${{ matrix.runner }}
      timeout: 120
      script: |
        set -euo pipefail
        
        # FIXME: Port this to pytorch/test-infra/.github/workflows/windows_job.yml
        export PATH="/c/Jenkins/Miniconda3/Scripts:${PATH}"

        export PYTHON_VERSION=${{ matrix.python-version }}
        export GPU_ARCH_TYPE=${{ matrix.gpu-arch-type }}
        export GPU_ARCH_VERSION=${{ matrix.gpu-arch-version }}
        
        ./.github/scripts/unittest.sh
