name: Update viable/strict

on:
  pull_request:
    paths:
      - .github/workflows/update-viablestrict.yml
  schedule:
    - cron: 10,40 * * * *
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  do_update_viablestrict:
    runs-on: ubuntu-20.04
    steps:
      - name: Update viable/strict
        uses: pytorch/test-infra/.github/actions/update-viablestrict@main
        with:
          repository: pytorch/vision
          stable-branch: viable/strict
          test-infra-ref: main
          requires: '[\"Build Linux\",\"Build M1\",\"Build Macos\",\"Build Windows\",\"Tests\",\"CMake\",\"Lint\",\"Docs\"]'
          rockset-api-key: ${{ secrets.ROCKSET_API_KEY }}
          secret-bot-token: ${{ secrets.VISION_GITHUB_DEPLOY_KEY }}
